version: '3'

services:
  api:
    image: 'alfa-api'
    ports:
      - "8181:8181"
    depends_on:
      alfadb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://alfadb:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  alfadb:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - APP_DB_USER=usuario
      - APP_DB_PASS=senha
      - APP_DB_NAME=alfa
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


